language: php

dist: trusty

php:
  - 7.1
  - 7.2

before_script:
  composer install

addons:
  sonarcloud:
    token:
      secure: "l5nFMypnxBzF5WbLHI9Gj+KiMStjxxtLTyLy51IP13RZB4kAGdHhGo8L2kx8TW16aCudZ6pcwx6jkSjp3zyHWlGdVVcndRlQuZrgdM2th4KiBI0vstH36RFrNiuTRqcMomOAmGNLwgbivpWI2OOax6AaANsdDMb5MY/1w4HOCukghA3WKK+WdvK9ZAkzu2/6Jiyfo4IC8WRhC26V3yMsZle5DWp1WV/ICPhFK7nFWxLH15p5N9SNmn6qYXDX6VxgzsxFWEuTOowwDmz5WdmmMdcbqoIfZPRBkvZt8UQSuzCKVKIt0JjrFTPC6mO0tH3q0DTa3ZFC3QJR+Kdve1CvtglKfzQG2yNJf12QmJ8BlwK+GoXhew5032lUH8zmMzULJy5/KgxdN7soC26w034xUTSBe7revuyHuzr7SbJUVtsFhxC/W1YNnmyF2TvcpBOWFJ0aA8jmEqtzSY8VmP86FkvvcRnkZYEDNNh4itWZylXKJJsgnl/dYbCd4Agmxz2tU77YedPWynNIx6AHo1osmwlvPPHCGjUwhx3Km6FqKfVTCcko2feKpMtBu8ETCVOLpNRPA3U7OJxFipRDgarFNz50XGtwkE0qGzsdhW7DTA1DLjpToSqeDEJ+YnltPYUe73o/mx/f67ObfYQFkNTDCNd7NE6rbcIHLKPBZ/BkNGE="

script:
  - sonar-scanner
