language: php

dist: trusty

php:
  - 7.1
  - 7.2

before_script:
  composer install

addons:
  sonarcloud:
    organization: "grgk-github"

script:
  - vendor/bin/phpunit --coverage-clover build/logs/phpunit/clover.xml --log-junit build/logs/phpunit/junit.xml --coverage-xml build/logs/phpunit/coverage/xml --coverage-html build/logs/phpunit/coverage/html
  - ./sonarphp-xml-patcher.py
  - sonar-scanner
